export const MEDICAL_SPECIALTIES = [
  'Acupuntura',
  'Alergia e Imunologia',
  'Anestesiologia',
  'Angiologia',
  'Cardiologia',
  'Cirurgia Cardiovascular',
  'Cirurgia da Mao',
  'Cirurgia de Cabeca e Pescoco',
  'Cirurgia do Aparelho Digestivo',
  'Cirurgia Geral',
  'Cirurgia Pediatrica',
  'Cirurgia Plastica',
  'Cirurgia Toracica',
  'Cirurgia Vascular',
  'Clinica Geral',
  'Clinica Medica',
  'Coloproctologia',
  'Dermatologia',
  'Endocrinologia',
  'Endoscopia',
  'Fisiatria',
  'Gastroenterologia',
  'Genetica Medica',
  'Geriatria',
  'Ginecologia e Obstetricia',
  'Harmonizacao Facial',
  'Hematologia',
  'Homeopatia',
  'Infectologia',
  'Mastologia',
  'Medicina de Familia',
  'Medicina do Trabalho',
  'Medicina Esportiva',
  'Medicina Intensiva',
  'Medicina Nuclear',
  'Nefrologia',
  'Neurocirurgia',
  'Neurologia',
  'Nutrologia',
  'Odontologia',
  'Oftalmologia',
  'Oncologia',
  'Ortopedia e Traumatologia',
  'Otorrinolaringologia',
  'Patologia',
  'Pediatria',
  'Pneumologia',
  'Psiquiatria',
  'Radiologia',
  'Radioterapia',
  'Reumatologia',
  'Urologia',
] as const;

export const HEALTH_SPECIALTIES = [
  'Biomedicina',
  'Educacao Fisica',
  'Enfermagem',
  'Farmacia',
  'Fisioterapia',
  'Fonoaudiologia',
  'Musicoterapia',
  'Nutricao',
  'Optometria',
  'Podologia',
  'Psicologia',
  'Psicopedagogia',
  'Quiropraxia',
  'Terapia Ocupacional',
] as const;

export type MedicalSpecialty = typeof MEDICAL_SPECIALTIES[number];
export type HealthSpecialty = typeof HEALTH_SPECIALTIES[number];
