-- Add new role values to Role enum
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'DOCTOR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'RECEPTIONIST';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'FINANCIAL';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'STOCK';
