-- Rename Plan enum values: ESSENTIAL→STARTER, PROFESSIONAL→PRO, ENTERPRISE→BUSINESS

-- Rename enum values first
ALTER TYPE "Plan" RENAME VALUE 'ESSENTIAL' TO 'STARTER';
ALTER TYPE "Plan" RENAME VALUE 'PROFESSIONAL' TO 'PRO';
ALTER TYPE "Plan" RENAME VALUE 'ENTERPRISE' TO 'BUSINESS';

-- Update default
ALTER TABLE "tenants" ALTER COLUMN "plan" SET DEFAULT 'STARTER'::"Plan";
